blueprints/landingPage/views.py
from flask import Blueprint, render_template, session, redirect, url_for, request
import mysql.connector
import dropbox
import random

# dropbox_access_token= "xogv50OrMysAAAAAAAAAAZLNZRmAmZXik0U4xaF6EoWmQlFMPiDuw6JmfxzDWTiF"
# dropbox_path= "/Apps/newTwitter"
# dbx = dropbox.Dropbox(dropbox_access_token)


# conn = mysql.connector.connect(host='freedb.tech',user='freedbtech_rsyst', password='zxcvbnml', database='freedbtech_rsyst')
# cursor = conn.cursor()

landingPage = Blueprint('landingPage',__name__, template_folder='templates', static_folder='static',static_url_path='landingPage/static')

@landingPage.route('/', methods=['POST', 'GET'])
def home():
	if "user" in session:
		return redirect(url_for('.feed'))
	else:
		if request.method=='POST':
			if request.form.get('name', False) and request.form.get('userid', False) and request.form.get('password', False) and request.form.get('month', False) and request.form.get('day', False) and request.form.get('year', False):
				name=request.form['name']
				userid = request.form['userid']
				password = request.form['password']
				month = request.form['month']
				day = request.form['day']
				year= request.form['year']
				#print(type(name), type(phoneNumber), type(password), type(month), type(day), type(year)) #all values are string

				conn = mysql.connector.connect(host='database-404.cljpc2llv9ft.ap-south-1.rds.amazonaws.com',user='admin', password='admin2114', database='newtwitter')
				cursor = conn.cursor()
				cursor.execute((" SELECT * FROM newtwitter_user WHERE userid='{}' ".format(userid)))
				user = cursor.fetchall()

				if user:
					return redirect(url_for('.signin'))
				else:
					cursor.execute(("INSERT INTO newtwitter_user (username, userid, password, dob) VALUES ('{}','{}','{}','{}')".format(name, userid,password,year+'-'+month+'-'+day)))
					conn.commit()
					return redirect(url_for('.signin'))

				return render_template('landingPage/newTwitter.html')
		return render_template('landingPage/newTwitter.html')

@landingPage.route('/signin', methods=['POST', 'GET'])
def signin():
	# return render_template('landingPage/signin.html')

	if "user" in session:
		return redirect(url_for('.feed'))
	else:
		if request.method=='POST':
			if request.form.get('userid', False) and request.form.get('password', False):
				userid = request.form['userid']
				password = request.form['password']
				
				conn = mysql.connector.connect(host='database-404.cljpc2llv9ft.ap-south-1.rds.amazonaws.com',user='admin', password='admin2114', database='newtwitter')
				cursor = conn.cursor()
				cursor.execute(("SELECT * FROM newtwitter_user WHERE userid='{}'".format(userid)))
				user = cursor.fetchall()

				if user:
					#checking if userid and pass match with those at database
					if user[0][1]==userid and user[0][2]==password:
						#creating session data
						session['user'] = user[0][1]
						return redirect(url_for('.feed'))
					else:
						return render_template('landingPage/signin.html')
				return render_template('landingPage/signin.html')
			return render_template('landingPage/signin.html')
					
		else:
			return render_template('landingPage/signin.html')

@landingPage.route('/dashboard')
def dashboard():
	if "user" in session:
		userid = session['user']
		conn = mysql.connector.connect(host='database-404.cljpc2llv9ft.ap-south-1.rds.amazonaws.com',user='admin', password='admin2114', database='newtwitter')
		cursor = conn.cursor()
		cursor.execute(("SELECT * FROM newtwitter_user WHERE userid='{}'".format(userid)))
		user = cursor.fetchall()

		cursor.execute(("SELECT * FROM newtwitter_comment WHERE userid='{}' ORDER BY toc DESC".format(userid)))
		comments = cursor.fetchall()
		try:
			# dp = dbx.files_get_temporary_link(f'/{userid}dp.jpg')
			# dp =dp.link
			dp = user[0][7]
			# cover = dbx.files_get_temporary_link(f'/{userid}cover.jpg')
			# cover = cover.link
			cover = user[0][8]
			
			return render_template('dashBoard/profile.html', data=(user,comments, [dp, cover]))
		except:
			return render_template('dashBoard/profile.html', data=(user,comments))

	else:
		return redirect(url_for('.signin'))

@landingPage.route('/home', methods=['GET', 'POST'])
def feed():
	if "user" in session:
		conn = mysql.connector.connect(host='database-404.cljpc2llv9ft.ap-south-1.rds.amazonaws.com',user='admin', password='admin2114', database='newtwitter')
		cursor = conn.cursor()
		cursor.execute(("SELECT newtwitter_comment.userid, newtwitter_user.username, newtwitter_comment.comments, newtwitter_comment.toc, newtwitter_user.dp_link FROM newtwitter_comment INNER JOIN newtwitter_user ON newtwitter_comment.userid=newtwitter_user.userid"))
		user_data = cursor.fetchall()
		random.shuffle(user_data)

		#user_info
		cursor.execute((" SELECT * FROM newtwitter_user where userid='{}' ".format(session['user'])))
		user_info = cursor.fetchall()
		return render_template('dashBoard/homepage.html', data=(user_data), user_info =user_info)
	return redirect(url_for('.signin'))

@landingPage.route('/logout', methods=['POST', 'GET'])
def logout():
	session.clear()
	return redirect(url_for('.signin'))
	

blueprints/landingPage/templates/landingPage/signin.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>Log in - newTwitter</title>

  <style>
    input:-webkit-autofill,
    input:-webkit-autofill:focus {
      -webkit-text-fill-color: white;
      -webkit-box-shadow: 0 0 0px 1000px #212529 inset;
    }
  </style>

</head>


<body class="bg-dark">


  <div class="row d-flex justify-content-center">

    <!-- <div class="col-2"></div> -->

    <div class="col-md-4">
      <div class="container">

        <div class="mt-3 mx-2" style="width: 100%;">
          <img class="img-fluid" src="{{url_for('landingPage.static', filename='img/twitter-512.png')}}"
            style="filter: invert(1); width: 38px; height: 40px;" alt="">
        </div>

        <div class="text-white p-0 m-0 mt-3 h2 fw-bold mx-2">Log in to newTwitter</div>

        <form method="post" action="{{ url_for('landingPage.signin')}}">

          <div class="form-floating my-4 mx-2">
            <input type="text" class="form-control border-muted bg-dark text-white" name="userid" id="loginId"
              placeholder="username" required autofocus>
            <label for="loginId" class="text-white">username</label>
          </div>

          <div class="form-floating mx-2">
            <input type="password" class="form-control border-muted bg-dark text-white" name="password" id="loginPasst"
              placeholder="Password" required>
            <label for="loginPass" class="text-white">Password</label>
          </div>

          <button type="submit" class="btn btn-block btn-primary w-100 text-white fw-bolder rounded-pill py-2  my-4">Log
            in</button>

        </form>

        <a href="{{url_for('landingPage.home')}}">
          <h1 class="small text-primary text-center">Sign up for newTwitter</h1>
        </a>


      </div>
    </div>

    <!-- <div class="col-2"></div> -->
  </div>




  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

</body>

</html>

blueprints/landingPage/templates/newTwitter.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Twitter</title>
    <link rel="stylesheet" href="{{ url_for('.static', filename='css/style.css') }}">
</head>

<body>
    <div id='left'>
        <img src="https://pngimg.com/uploads/twitter/twitter_PNG1.png" />
    </div>

    <div id="right">

        <div id="info">
            <h1>Happening Now.</h1>
            <h2>Join newTwitter today.</h2>
            <button id="login">Log In</button>
            <button id="signup" onclick="openForm()">Sign Up</button>
        </div>

        <!-- <div id="button">
        </div> -->

    </div>

    <footer>
        <a>About</a>
        <a>help Center</a>
        <a>Terms of Service</a>
        <a>Privacy Policy</a>
        <a>Cookie policy</a>
        <a>Ads info</a>
        <a>Blog</a>
        <a>Status</a>
        <a>Careers</a>
        <a>Brand Resources</a>
        <a>Advertising</a>
        <a>Marketing</a>
        <a>newTwitter for Business</a>
        <a>Developers</a>
        <a>Directory</a>
        <a>Settings</a>
        <a>© 2021 Twitter, Inc.</a>
    </footer>


    <div id="formContainer" class="formContainer">

        <div class="form">
            <div class="formHead">
                <div id="imgdiv">
                    <img id="logosmall" src="https://pngimg.com/uploads/twitter/twitter_PNG1.png">
                </div>
                <div id="btndiv">
                    <button id="nextsignup">SignUp</button>
                </div>
            </div>

            <div class="formBody">

                <label id="labelname" for="name">Create your account</label>
                <input id="name" type="text" placeholder="Name" value="" required>
                <input id="phone" type="number" placeholder="Number" value="" required>
                
                <div #dobinfo>
                    <h4>Date of Birth</h4>
                    <p>This will not be shown publicly. Confirm your own age, even if this account is for a business, a
                    pet, or something else.</p>
                </div>
                <div id="dob">
                    <select id="month">
                        <option value="1">Jan</option>
                        <option value="2">Feb</option>
                        <option value="3">Mar</option>
                        <option value="4">Apr</option>
                        <option value="5">May</option>
                        <option value="6">Jun</option>
                        <option value="7">Jul</option>
                        <option value="8">Aug</option>
                        <option value="9">Sep</option>
                        <option value="10">Oct</option>
                        <option value="11">Nov</option>
                        <option value="12">Dec</option>
                    </select>

                    <select id="day">
                        <option value="">Day</option>
                        <option value="">---</option>
                        <option value="01">01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                    </select>
                    <select id="year">
                        <option>Year</option>
                        <option value="2021">2021</option>
                        <option value="2020">2020</option>
                        <option value="2019">2019</option>
                        <option value="2018">2018</option>
                        <option value="2017">2017</option>
                        <option value="2016">2016</option>
                        <option value="2015">2015</option>
                        <option value="2014">2014</option>
                        <option value="2013">2013</option>
                        <option value="2012">2012</option>
                        <option value="2011">2011</option>
                        <option value="2010">2010</option>
                        <option value="2009">2009</option>
                        <option value="2008">2008</option>
                        <option value="2007">2007</option>
                        <option value="2006">2006</option>
                        <option value="2005">2005</option>
                        <option value="2004">2004</option>
                        <option value="2003">2003</option>
                        <option value="2002">2002</option>
                        <option value="2001">2001</option>
                        <option value="2000">2000</option>
                        <option value="1999">1999</option>
                        <option value="1998">1998</option>
                        <option value="1997">1997</option>
                        <option value="1996">1996</option>
                        <option value="1995">1995</option>
                        <option value="1994">1994</option>
                        <option value="1993">1993</option>
                        <option value="1992">1992</option>
                        <option value="1991">1991</option>
                        <option value="1990">1990</option>
                        <option value="1989">1989</option>
                        <option value="1988">1988</option>
                        <option value="1987">1987</option>
                        <option value="1986">1986</option>
                        <option value="1985">1985</option>
                        <option value="1984">1984</option>
                        <option value="1983">1983</option>
                        <option value="1982">1982</option>
                        <option value="1981">1981</option>
                        <option value="1980">1980</option>
                        <option value="1979">1979</option>
                        <option value="1978">1978</option>
                        <option value="1977">1977</option>
                        <option value="1976">1976</option>
                        <option value="1975">1975</option>
                        <option value="1974">1974</option>
                        <option value="1973">1973</option>
                        <option value="1972">1972</option>
                        <option value="1971">1971</option>
                        <option value="1970">1970</option>
                        <option value="1969">1969</option>
                        <option value="1968">1968</option>
                        <option value="1967">1967</option>
                        <option value="1966">1966</option>
                        <option value="1965">1965</option>
                        <option value="1964">1964</option>
                        <option value="1963">1963</option>
                        <option value="1962">1962</option>
                        <option value="1961">1961</option>
                        <option value="1960">1960</option>
                        <option value="1959">1959</option>
                        <option value="1958">1958</option>
                        <option value="1957">1957</option>
                        <option value="1956">1956</option>
                        <option value="1955">1955</option>
                        <option value="1954">1954</option>
                        <option value="1953">1953</option>
                        <option value="1952">1952</option>
                        <option value="1951">1951</option>
                        <option value="1950">1950</option>
                        <option value="1949">1949</option>
                        <option value="1948">1948</option>
                        <option value="1947">1947</option>
                        <option value="1946">1946</option>
                        <option value="1945">1945</option>
                        <option value="1944">1944</option>
                        <option value="1943">1943</option>
                        <option value="1942">1942</option>
                        <option value="1941">1941</option>
                        <option value="1940">1940</option>
                        <option value="1939">1939</option>
                        <option value="1938">1938</option>
                        <option value="1937">1937</option>
                        <option value="1936">1936</option>
                        <option value="1935">1935</option>
                        <option value="1934">1934</option>
                        <option value="1933">1933</option>
                        <option value="1932">1932</option>
                        <option value="1931">1931</option>
                        <option value="1930">1930</option>
                        <option value="1929">1929</option>
                        <option value="1928">1928</option>
                        <option value="1927">1927</option>
                        <option value="1926">1926</option>
                        <option value="1925">1925</option>
                        <option value="1924">1924</option>
                        <option value="1923">1923</option>
                        <option value="1922">1922</option>
                        <option value="1921">1921</option>
                        <option value="1920">1920</option>
                        <option value="1919">1919</option>
                        <option value="1918">1918</option>
                        <option value="1917">1917</option>
                        <option value="1916">1916</option>
                        <option value="1915">1915</option>
                        <option value="1914">1914</option>
                        <option value="1913">1913</option>
                        <option value="1912">1912</option>
                        <option value="1911">1911</option>
                        <option value="1910">1910</option>
                        <option value="1909">1909</option>
                        <option value="1908">1908</option>
                        <option value="1907">1907</option>
                        <option value="1906">1906</option>
                        <option value="1905">1905</option>
                        <option value="1904">1904</option>
                        <option value="1903">1903</option>
                        <option value="1902">1902</option>
                        <option value="1901">1901</option>
                        <option value="1900">1900</option>
                    </select>
                </div>

            </div>
        </div>
    </div>




    <!-- popup func -->
    <script>
        function openForm(){
            document.getElementById("formContainer").style.display="flex";
        }
    </script>
</body>

</html>